/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interfaces;

import Classes.Validation;
import Event_Classes.Ad_payment;
import Event_Classes.Advertisment;
import Event_Classes.dbconnct;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Navodya
 */
public class AddAds extends javax.swing.JInternalFrame {
    
        Connection con= dbconnct.connect();
        PreparedStatement pst=null;
        ResultSet rs = null;
        
        Advertisment a= new Advertisment();
        Ad_payment  ap = new Ad_payment();
    /**
     * Creates new form AddAds
     */
    public AddAds() {
        initComponents();
        con=dbconnct.connect();
        
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        if(amPm.equals("PM")){
        getContentPane().setBackground(Color.lightGray);
        }
        else
          getContentPane().setBackground(Color.decode("#F5F5F5"));  
        tableload();
    }
    public void tableload(){
    
          try{
            String sql1 = "SELECT ad_id AS 'Advertisment ID' FROM advertisments";
            
            pst=con.prepareStatement(sql1);
            rs=pst.executeQuery();
        
            apay.setModel(DbUtils.resultSetToTableModel(rs));
           }
           
           catch(Exception e){
               
                System.out.println(e);
           }
    
          
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ban = new javax.swing.JRadioButton();
        bill = new javax.swing.JRadioButton();
        ee = new javax.swing.JRadioButton();
        fg = new javax.swing.JRadioButton();
        k = new javax.swing.JRadioButton();
        tv = new javax.swing.JRadioButton();
        lcd = new javax.swing.JComboBox<String>();
        kiosk = new javax.swing.JComboBox<String>();
        floor = new javax.swing.JComboBox<String>();
        esc = new javax.swing.JComboBox<String>();
        billboard = new javax.swing.JComboBox<String>();
        banner = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        per = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        apay = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pro = new javax.swing.JCheckBox();
        sal = new javax.swing.JCheckBox();
        seve = new javax.swing.JCheckBox();
        market = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add Advertisments");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setText("Advertisment ID");

        adId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setText("Location");

        ban.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ban.setText("Banners");
        ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banActionPerformed(evt);
            }
        });

        bill.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        bill.setText("BillBoard");

        ee.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ee.setText("Escalators and Elevator wraps");

        fg.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        fg.setText("Floor Graphics");

        k.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        k.setText("Kiosks");

        tv.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        tv.setText("LCD Panel");

        lcd.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        lcd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LCD Panel", "32", "40", "43", "50" }));
        lcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcdActionPerformed(evt);
            }
        });

        kiosk.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        kiosk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kiosks", "10 feet ", "7 feet", "3 feet", " " }));

        floor.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        floor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Floor Graphics", "Carpet Graphics", "Custom Shape", "Sidewalk", "Outdoor" }));
        floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorActionPerformed(evt);
            }
        });

        esc.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        esc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escalator and Elevator wraps", "Pannel", "Fins" }));

        billboard.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        billboard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BillBoard", "40 X 60", "120 X 60", "80 X 120", "240 X 120" }));
        billboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billboardActionPerformed(evt);
            }
        });

        banner.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        banner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banners", "Full Banner 20KB 480 x 60", "LeaderBoard 25KB 728 x 280", "Square 20KB 336 x 280", "Skyscraper 20KB 120 x 240" }));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("Period");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel11.setText("Description");

        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        des.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                desKeyTyped(evt);
            }
        });

        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel9.setText("( in weeks )");

        apay.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        apay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        apay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(apay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(166, 166, 166)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ee))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(427, 427, 427)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fg))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kiosk, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(k))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tv)
                                            .addComponent(lcd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addGap(468, 468, 468)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ban)
                                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(adId, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ban)
                            .addComponent(bill)
                            .addComponent(ee)
                            .addComponent(fg)
                            .addComponent(k)
                            .addComponent(tv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kiosk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel8.setText("Type of advertisment");

        pro.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        pro.setText("Promotions");

        sal.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        sal.setText("Sales");
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });

        seve.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        seve.setText("Special  Evennts");
        seve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seveActionPerformed(evt);
            }
        });

        market.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        market.setText("Brand/Shop Markrtings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sal)
                .addGap(104, 104, 104)
                .addComponent(seve)
                .addGap(90, 90, 90)
                .addComponent(market)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seve)
                        .addComponent(market)
                        .addComponent(sal))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pro)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jButton4.setText("Demo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(jButton3)
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adIdActionPerformed

    private void lcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcdActionPerformed

    private void floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorActionPerformed

    private void billboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billboardActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed

    private void seveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
         if(adId.getText().isEmpty() || per.getText().isEmpty() || des.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
        }
         else{
             Validation v=new Validation();
             
             if(v.isNumeric(adId.getText())){
            JOptionPane.showMessageDialog(null,"Enter event ID  again!");
            }else if(!v.isNumeric(per.getText())){
            JOptionPane.showMessageDialog(null,"Enter event title again!");
            }else if((v.isNumeric(des.getText()))){
            JOptionPane.showMessageDialog(null,"Enter descripton correctly!");
            }
            else{
             a.setAdvertismentID(adId.getText());
            char c=a.getAdvertismentID().charAt(0);
                if(c!='A'){
                JOptionPane.showMessageDialog(null,"Incorrect primary  key input");

                 }
                else{
                    if(ban.isSelected())
                 {
                        a.setLocation(ban.getText());
                        a.setType(banner.getSelectedItem().toString());

                     }
                    else if(bill.isSelected())
                    {
                        a.setLocation(bill.getText());
                        a.setType(billboard.getSelectedItem().toString());

                    }
                    else if(ee.isSelected())
                    {
                        a.setLocation(ee.getText());
                        a.setType(esc.getSelectedItem().toString());

                    }
                    else if(fg.isSelected())
                    {
                        a.setLocation(fg.getText());
                        a.setType(floor.getSelectedItem().toString());

                    }

                    else if(k.isSelected())
                    {
                         a.setLocation(k.getText());
                         a.setType(kiosk.getSelectedItem().toString());

                    }

                     else if(tv.isSelected())
                    {
                         a.setLocation(tv.getText());
                         a.setType(lcd.getSelectedItem().toString());
                
                     }
                    else
                        JOptionPane.showMessageDialog(null,"Incorrect Input");
            
                    if(pro.isSelected())
                         a.setaType(pro.getText());

                    else if(sal.isSelected())
                        a.setaType(sal.getText());

                    else if(seve.isSelected())
                        a.setaType(seve.getText());

                    else if(market.isSelected())
                        a.setaType(market.getText());

                    else
                        JOptionPane.showMessageDialog(null,"Please choose only one");
            
                        a.setPeriod(Integer.parseInt(per.getText()));
                        a.setDescription(des.getText());
                       
                        if(a.addAd(a.getAdvertismentID(),a.getPeriod(),a.getDescription(),a.getaType(),a.getLocation(),a.getType())==true){
                            
                        //a.adLoc(a.getLocation(),a.getType()); //  public void calPay(String aid,String loc,String Ty,String adTy,int p,String d)
                            ap.calPay(a.getAdvertismentID(),a.getLocation(),a.getType(),a.getaType(),a.getPeriod(),a.getDescription());
                        }
                        tableload();
                }
            }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void perKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perKeyTyped
        // TODO add your handling code here:
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!"); }
    }                            

    private void phKeyTyped(java.awt.event.KeyEvent evt) {                            
        // TODO add your handling code here:
         if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
        //text.setEditable(true);
        //label.setText(""); 
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!"); }
    }//GEN-LAST:event_perKeyTyped

    private void desKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_desKeyTyped

    private void banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banActionPerformed

    private void apayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apayMouseClicked
        // TODO add your handling code here:

      
    }//GEN-LAST:event_apayMouseClicked

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
	des.setText("OPPO F1 camera phone Promotion");
        per.setText("5");
        pro.setSelected(true);
        ee.setSelected(true);
        esc.setSelectedItem("Pannel");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adId;
    private javax.swing.JTable apay;
    private javax.swing.JRadioButton ban;
    private javax.swing.JComboBox<String> banner;
    private javax.swing.JRadioButton bill;
    private javax.swing.JComboBox<String> billboard;
    private javax.swing.JTextField des;
    private javax.swing.JRadioButton ee;
    private javax.swing.JComboBox<String> esc;
    private javax.swing.JRadioButton fg;
    private javax.swing.JComboBox<String> floor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton k;
    private javax.swing.JComboBox<String> kiosk;
    private javax.swing.JComboBox<String> lcd;
    private javax.swing.JCheckBox market;
    private javax.swing.JTextField per;
    private javax.swing.JCheckBox pro;
    private javax.swing.JCheckBox sal;
    private javax.swing.JCheckBox seve;
    private javax.swing.JRadioButton tv;
    // End of variables declaration//GEN-END:variables
}
