/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event_Interfaces;

import Classes.Validation;
import Event_Classes.dbconnct;
import Event_Classes.EAManager;
import Event_Classes.Event;
import Event_Classes.organizer;
import com.teknikindustries.bulksms.SMS;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Navodya
 */
public class viewEvent extends javax.swing.JInternalFrame {

            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
             
        
            EAManager u = new EAManager();
            Event e= new Event();
            organizer o= new organizer();
    /**
     * Creates new form viewEvent
     */
    public viewEvent() {
        initComponents();
        con = dbconnct.connect(); 
        
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        if(amPm.equals("PM")){
        getContentPane().setBackground(Color.lightGray);
        }
        else
          getContentPane().setBackground(Color.decode("#F5F5F5"));  
    }
     public void sendmsg(){
    
        SMS send =new SMS();
        send.SendSMS("anuththarar", "squaregarden", "Dear Customer, This message is to inform you that your event details have been updated.  -Thank you- SGSM Staff",""+o.getPhoneNo()+"","https://bulksms.vsms.net/eapi/submission/send_sms/2/2.0");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contp = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        orgaID = new javax.swing.JTextField();
        oname = new javax.swing.JTextField();
        fno = new javax.swing.JTextField();
        oemail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eventType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        eventID = new javax.swing.JTextField();
        etitle = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        evlocation = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        locID = new javax.swing.JTextField();
        evStart = new com.toedter.calendar.JDateChooser();
        evEnd = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chairNum = new javax.swing.JTextField();
        tableNum = new javax.swing.JTextField();
        oilLNum = new javax.swing.JTextField();
        projNum = new javax.swing.JTextField();
        sceeNum = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        select = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Update Information");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Organizers Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel7.setText("Organizer ID");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel8.setText("Fax No");

        contp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contpActionPerformed(evt);
            }
        });
        contp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contpKeyTyped(evt);
            }
        });

        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });
        ph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel18.setText("Phone No");

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel19.setText("Name");

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel20.setText("Contact person");

        jLabel21.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel21.setText("Email");

        oname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onameKeyTyped(evt);
            }
        });

        fno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orgaID, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(oname)
                    .addComponent(contp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(oemail, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ph, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(fno))))
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(orgaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(oemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(oname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(contp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Event Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setText("Event ID");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("Event Title");

        eventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Exhibition", "Bridal show", "Book fair", "Conference", "Motor Shows", "Pro food", "Architect", "Musical show", "Social event", "Movie Premiers", "Other(verify below)" }));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setText("Event type");

        eventID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventIDActionPerformed(evt);
            }
        });

        etitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etitleActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel17.setText("End date");

        jLabel16.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel16.setText("Start Date");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel6.setText("Select Location");

        evlocation.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        evlocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "locations", "Banquet Hall", "Cocktail Lounge", "OutDoor", "Exhibition Hall", "Open Area", "Function Hall", " " }));

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel15.setText("Location ID");

        locID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(etitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(eventType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(eventID)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(locID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(evlocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(evStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(evEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(29, 29, 29)))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eventID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(evlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(locID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(evStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(evEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel9.setText("Accessories Required");

        jLabel10.setText("No:");

        jLabel11.setText("No:");

        jLabel12.setText("No:");

        jLabel13.setText("No:");

        jLabel14.setText("No:");

        oilLNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilLNumActionPerformed(evt);
            }
        });

        sceeNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sceeNumActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel26.setText("Banquet chairs");

        jLabel25.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel25.setText("Tables");

        jLabel24.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel24.setText("Oil Lamps");

        jLabel23.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel23.setText("Projectors");

        jLabel22.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel22.setText("Screens");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chairNum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oilLNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sceeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(projNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(sceeNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(tableNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(oilLNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chairNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        select.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Search type---", "Event ID", "Organizer ID", "Event title", "Organizer name" }));

        Search.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(687, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Search)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(456, 456, 456))
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contpActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phActionPerformed

    private void eventIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventIDActionPerformed

    private void etitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etitleActionPerformed

    private void locIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locIDActionPerformed

    private void oilLNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilLNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oilLNumActionPerformed

    private void sceeNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sceeNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sceeNumActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
        
        
        if(select.getSelectedItem().equals("Event ID")){
                
                 e.setEventId(search.getText());
                 String sq4 = "SELECT * FROM event e, organizer o,accerssories a,location l WHERE e.orgID=o.orgId  AND e.event_id=a.eventID AND e.locID=l.LocId AND E.event_id='"+ e.getEventId() +"'";
                 try{
                        pst = con.prepareStatement(sq4); //need to  access three tables 
                        rs = pst.executeQuery();
                        rs.next();
                 
                        eventID.setText(rs.getString("event_id"));
                        etitle.setText(rs.getString("title"));
                        eventType.setSelectedItem(rs.getString("eventType")); 
                        locID.setText(rs.getString("locID"));
                        evlocation.setSelectedItem(rs.getString("loca"));
                        evStart.setDate(rs.getDate("startDate"));
                        evEnd.setDate(rs.getDate("endDate"));
                        
                        orgaID.setText(rs.getString("orgId"));
                        oname.setText(rs.getString("oname"));
                        contp.setText(rs.getString("contactPerson"));
                        oemail.setText(rs.getString("email"));
                        ph.setText(rs.getString("phoneno"));
                        fno.setText(rs.getString("faxno"));
                        
                        chairNum.setText(rs.getString("Banquet_chairs"));
                        tableNum.setText(rs.getString("Tables"));
                        oilLNum.setText(rs.getString("Oil_Lamps"));
                        projNum.setText(rs.getString("Projectors"));
                        sceeNum.setText(rs.getString("Screens"));
                        
                        
                 }
                 catch(SQLException e){
                 
                      JOptionPane.showMessageDialog(null,"Incorrect Value"+e);
                 
                 }
        }
        else if(select.getSelectedItem().equals("Organizer ID")){
        
            o.setOrganizerID(search.getText());
            String sq4 = "SELECT * FROM event e, organizer o,accerssories a,location l WHERE e.orgID=o.orgId  AND e.event_id=a.eventID AND e.locID=l.LocId AND e.event_Id='"+ o.getOrganizerID() +"'";
                 try{
                        pst = con.prepareStatement(sq4); //need to  access three tables 
                        rs = pst.executeQuery();
                        rs.next();
                 
                        eventID.setText(rs.getString("event_id"));
                        etitle.setText(rs.getString("title"));
                        eventType.setSelectedItem(rs.getString("eventType")); 
                        locID.setText(rs.getString("locID"));
                        evlocation.setSelectedItem(rs.getString("loca"));
                        evStart.setDate(rs.getDate("startDate"));
                        evEnd.setDate(rs.getDate("endDate"));
                        
                        orgaID.setText(rs.getString("orgId"));
                        oname.setText(rs.getString("oname"));
                        contp.setText(rs.getString("contactPerson"));
                        oemail.setText(rs.getString("email"));
                        ph.setText(rs.getString("phoneno"));
                        fno.setText(rs.getString("faxno"));
                        
                        chairNum.setText(rs.getString("Banquet_chairs"));
                        tableNum.setText(rs.getString("Tables"));
                        oilLNum.setText(rs.getString("Oil_Lamps"));
                        projNum.setText(rs.getString("Projectors"));
                        sceeNum.setText(rs.getString("Screens"));
                 }
                 catch(Exception e){
                 
                  JOptionPane.showMessageDialog(null,"Incorrect Value"+e);
                 }
        
        }
        else if(select.getSelectedItem().equals("Event title")){
          
            e.setTitle(search.getText());
            String sq4 = "SELECT * FROM event e, organizer o,accerssories a,location l WHERE e.orgID=o.orgId AND e.event_id=a.eventID AND e.locID=l.LocId AND e.title='"+ e.getTitle() +"'";
                 try{
                        pst = con.prepareStatement(sq4); //need to  access three tables 
                        rs = pst.executeQuery();
                        rs.next();
                 
                        eventID.setText(rs.getString("event_id"));
                        etitle.setText(rs.getString("title"));
                        eventType.setSelectedItem(rs.getString("eventType")); 
                        locID.setText(rs.getString("locID"));
                        evlocation.setSelectedItem(rs.getString("loca"));
                        evStart.setDate(rs.getDate("startDate"));
                        evEnd.setDate(rs.getDate("endDate"));
                        
                        orgaID.setText(rs.getString("orgId"));
                        oname.setText(rs.getString("oname"));
                        contp.setText(rs.getString("contactPerson"));
                        oemail.setText(rs.getString("email"));
                        ph.setText(rs.getString("phoneno"));
                        fno.setText(rs.getString("faxno"));
                        
                        chairNum.setText(rs.getString("Banquet_chairs"));
                        tableNum.setText(rs.getString("Tables"));
                        oilLNum.setText(rs.getString("Oil_Lamps"));
                        projNum.setText(rs.getString("Projectors"));
                        sceeNum.setText(rs.getString("Screens"));
                 }
                 catch(Exception e){
                 
                  JOptionPane.showMessageDialog(null,"Incorrect Value"+e);
                 }
        }
        else if(select.getSelectedItem().equals("Organizer name")){
          
            o.setName(search.getText());
            String sq4 = "SELECT * FROM event e, organizer o,accerssories a,location l WHERE e.orgID=o.orgId  AND e.event_id=a.eventID AND e.locID=l.LocId AND o.oname='"+ o.getName() +"'";
                 try{
                        pst = con.prepareStatement(sq4); //need to  access three tables 
                        rs = pst.executeQuery();
                        rs.next();
                 
                        eventID.setText(rs.getString("event_id"));
                        etitle.setText(rs.getString("title"));
                        eventType.setSelectedItem(rs.getString("eventType")); 
                        locID.setText(rs.getString("locID"));
                        evlocation.setSelectedItem(rs.getString("loca"));
                        evStart.setDate(rs.getDate("startDate"));
                        evEnd.setDate(rs.getDate("endDate"));
                        
                        orgaID.setText(rs.getString("orgId"));
                        oname.setText(rs.getString("oname"));
                        contp.setText(rs.getString("contactPerson"));
                        oemail.setText(rs.getString("email"));
                        ph.setText(rs.getString("phoneno"));
                        fno.setText(rs.getString("faxno"));
                        
                        chairNum.setText(rs.getString("Banquet_chairs"));
                        tableNum.setText(rs.getString("Tables"));
                        oilLNum.setText(rs.getString("Oil_Lamps"));
                        projNum.setText(rs.getString("Projectors"));
                        sceeNum.setText(rs.getString("Screen"));
                 }
                 catch(Exception e){
                 
                  JOptionPane.showMessageDialog(null,"Incorrect Value"+e);
                 }
        
        }//Event ID Organizer ID Event title Organizer name
        
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          
           String startD;
           String endD;
           
          if(eventID.getText().isEmpty() || etitle.getText().isEmpty() || locID.getText().isEmpty() || orgaID.getText().isEmpty() || oname.getText().isEmpty() || contp.getText().isEmpty() || ph.getText().isEmpty() || eventType.getSelectedItem().toString().isEmpty() || chairNum.getText().isEmpty() || evlocation.getSelectedItem().toString().isEmpty() || tableNum.getText().isEmpty() || oilLNum.getText().isEmpty() || projNum.getText().isEmpty()|| sceeNum.getText().isEmpty() || oemail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
            }
          else{
           int x= JOptionPane.showConfirmDialog(null,"Do you  really want to  update?");
       
            if(x==0){
                Validation v = new Validation();
                
            if(v.isNumeric(etitle.getText())){
            JOptionPane.showMessageDialog(null,"Enter event title again!");
            }else if(v.isNumeric(oname.getText())){  
            JOptionPane.showMessageDialog(null,"Enter organizer name again!");
            }else if(v.isNumeric(contp.getText())){  
            JOptionPane.showMessageDialog(null,"Enter person`s name again!");
            }else if((ph.getText().length()!=11)){  
            JOptionPane.showMessageDialog(null,"Enter correct number again!");
            }else if(!v.isVaildContactNo(fno.getText())){  
            JOptionPane.showMessageDialog(null,"Enter correct number again!");
            }else if(!v.isNumeric(chairNum.getText())){
            JOptionPane.showMessageDialog(null,"Enter a number again!");
            }else if(!v.isNumeric(tableNum.getText())){
            JOptionPane.showMessageDialog(null,"Enter a number again!!");
            }else if(!v.isNumeric(oilLNum.getText())){  
            JOptionPane.showMessageDialog(null,"Enter a number again!!");
            }else if(!v.isNumeric(projNum.getText())){  
            JOptionPane.showMessageDialog(null,"Enter a number again!!");
            }else if(!v.isNumeric(sceeNum.getText())){  
            JOptionPane.showMessageDialog(null,"Enter a number again!!");
            }
            else{
            e.setEventId(eventID.getText());
            e.setTitle(etitle.getText());
            e.setLocation_ID(locID.getText());
            e.setEvent_Location(evlocation.getSelectedItem().toString());
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            e.setStartDate(dateFormat.format(evStart.getDate()));
            
            SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd"); 
            e.setEndDate(dateFormat2.format(evEnd.getDate()));
            
            o.setOrganizerID(orgaID.getText());
            o.setName(oname.getText());
            o.setContactsPerson(contp.getText());
            o.setPhoneNo(ph.getText());
            o.setFaxNo(fno.getText());
            
            eventID.setEditable(false);
            orgaID.setEditable(false);
            locID.setEditable(false);
            evlocation.setEditable(false);
            
            try {
                        if(u.update_event(e.getEventId(),e.getTitle(),e.getEvent_Type(),e.getLocation_ID(),e.getStartDate(),e.getEndDate(),e.getEvent_Location(),o.getOrganizerID())==true){
                        
                            o.updateOr(o.getOrganizerID(),o.getName(),o.getContactsPerson(),o.getEmail(),o.getPhoneNo(),o.getFaxNo());
                            sendmsg();
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(viewEvent.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
           }
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void onameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onameKeyTyped
        // TODO add your handling code here:
        

       
    }//GEN-LAST:event_onameKeyTyped

    private void contpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contpKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contpKeyTyped

    private void fnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnoKeyTyped
        // TODO add your handling code here:
         if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
        //text.setEditable(true);
        //label.setText(""); 
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!"); }
    }//GEN-LAST:event_fnoKeyTyped

    private void phKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phKeyTyped
        // TODO add your handling code here:
         if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
        //text.setEditable(true);
        //label.setText(""); 
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!"); }
    }//GEN-LAST:event_phKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        eventID.setText("");
        etitle.setText("");
        eventType.setSelectedItem(null);
        evStart.setDate(null);
        evEnd.setDate(null);
        evlocation.setSelectedItem(null);
        locID.setText("");
        evlocation.setSelectedItem(null);
        orgaID.setText("");
        oname.setText("");
        contp.setText("");
        oemail.setText("");
        ph.setText("");
        fno.setText("");
        chairNum.setText("");
        tableNum.setText("");
        oilLNum.setText("");
        projNum.setText("");
        sceeNum.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JTextField chairNum;
    private javax.swing.JTextField contp;
    private javax.swing.JTextField etitle;
    private com.toedter.calendar.JDateChooser evEnd;
    private com.toedter.calendar.JDateChooser evStart;
    private javax.swing.JTextField eventID;
    private javax.swing.JComboBox<String> eventType;
    private javax.swing.JComboBox<String> evlocation;
    private javax.swing.JTextField fno;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField locID;
    private javax.swing.JTextField oemail;
    private javax.swing.JTextField oilLNum;
    private javax.swing.JTextField oname;
    private javax.swing.JTextField orgaID;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField projNum;
    private javax.swing.JTextField sceeNum;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JTextField tableNum;
    // End of variables declaration//GEN-END:variables
}
