/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TandIn;

//import classes.DBconnect;
//import classes.Inventoryc;
//import classes.TandIManager;
import Classes.TandIManager;
import Classes.Charge;
import Classes.*;
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.PreparedStatement;
import db.dbconnct;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author HP
 */
public class Charges extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    Charge c = new Charge();
    
    TandIManager ti= new TandIManager();
    Validation va= new Validation();
    
    
 
    

    /**
     * Creates new form Charges
     */
    public Charges() {
        initComponents();
        
        //changes the form background color according to time
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        if(amPm.equals("PM")){
        getContentPane().setBackground(Color.lightGray);
        }
        else
          getContentPane().setBackground(Color.decode("#F5F5F5"));  
        
       
        
        conn = dbconnct.connect();
        
        //load table
        tableload();
       // tableload1();
        
    }
    
    public void tableload(){
        
        try{
             
            String sql = "SELECT  vehi_num as 'Vehicle No.',amount as 'Amount',exp_type as 'Expense Type' FROM trans_exp";
           pst = (PreparedStatement) conn.prepareStatement(sql);
           rs =pst.executeQuery();
           
           vctable.setModel(DbUtils.resultSetToTableModel(rs));
           
           
           
        }
        catch(Exception e){
            
        }
        
    
    }
    public void tableload1(){
        
        try{
             
            String sql = "SELECT request_id as 'Request id',req as 'Request',amount as 'Amount',status as 'Status' FROM request";
           pst = (PreparedStatement) conn.prepareStatement(sql);
           rs =pst.executeQuery();
           
           Rtable.setModel(DbUtils.resultSetToTableModel(rs));
           
           
        }
        catch(Exception e){
            
        }
        
    
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rqst = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        request = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        vn = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        amnt = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        ty = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        spntdate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rtable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        vctable = new javax.swing.JTable();

        p2.setBackground(new java.awt.Color(0, 153, 153));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p2.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request ");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount");

        rqst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rqstActionPerformed(evt);
            }
        });

        request.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        request.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Upload_26px_1.png")); // NOI18N
        request.setText("Request");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rqst, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(amount)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(request)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rqst, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(request, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        p3.setBackground(new java.awt.Color(0, 153, 153));
        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        l1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Vehicle Number");

        vn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Amount");

        amnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amntKeyTyped(evt);
            }
        });

        l3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Spent Date");

        add.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Add_New_26px_10.png")); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        l4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Type");

        ty.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        ty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Type", "Fuel", "Maintenance", "Service", " ", " " }));
        ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyActionPerformed(evt);
            }
        });

        l5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Payment Id");

        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vn)
                                .addComponent(amnt)
                                .addComponent(spntdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amnt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spntdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ty))
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Rtable);

        vctable.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        vctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        vctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vctableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vctable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        boolean x = va.isValidVehiNum(vn.getText());
         
         if(x==true)
         {
             vn.getText();
             
             
         }
          else
            JOptionPane.showMessageDialog(null," Invalid vehicle number");
        
        if(vn.getText().isEmpty() || amnt.getText().isEmpty() || pay.getText().isEmpty() || ty.getSelectedIndex()==-1)
                         JOptionPane.showMessageDialog(null,"Please fill all the fields");
       else{
       c.vehicleNo = vn.getText();
       c.amount = Double.parseDouble(amnt.getText());
       c.type=ty.getSelectedItem().toString();
       c.pid=pay.getText();
       
       SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
       c.date=dateFormat.format(spntdate.getDate());
     
       ti.addCharges(c.vehicleNo,c.amount,c.date,c.type,c.pid);
       tableload();
       
       }

    }//GEN-LAST:event_addActionPerformed

    private void tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyActionPerformed

    private void vnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_payActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        boolean x = va.isValidVehiNum(vn.getText());
         
         if(x==true)
         {
             vn.getText();
             
             
         }
          else
            JOptionPane.showMessageDialog(null," Invalid vehicle number");
        
        if(vn.getText().isEmpty() || amnt.getText().isEmpty() || pay.getText().isEmpty() || ty.getSelectedIndex()==-1)
                         JOptionPane.showMessageDialog(null,"Please fill all the fields");
       else{
       c.vehicleNo = vn.getText();
       c.amount = Double.parseDouble(amnt.getText());
       c.type=ty.getSelectedItem().toString();
       c.pid=pay.getText();
       
       SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
       c.date=dateFormat.format(spntdate.getDate());
       
       ti.updatecharges(c.pid,c.amount,c.date,c.vehicleNo,c.type);
       tableload();
       }// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void amntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amntKeyTyped
       
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
        //text.setEditable(true);
        //label.setText(""); 
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!");
    }//GEN-LAST:event_amntKeyTyped
    }
    private void rqstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rqstActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_rqstActionPerformed

    private void vctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vctableMouseClicked
        int r = vctable.getSelectedRow();
        
        String vnum = vctable.getValueAt(r, 0).toString();
        String amont = vctable.getValueAt(r, 1).toString();
        String type = vctable.getValueAt(r, 2).toString();
        
        
        rqst.setText(type);
        amount.setText(amont);
       
        String sq="SELECT  vehi_num,amount,date,exp_type,pid FROM trans_exp WHERE vehi_num='" +vnum +"'";
        try{ 
            pst = (PreparedStatement) conn.prepareStatement(sq);
            rs =pst.executeQuery();
            rs.next();
        
            vn.setText(rs.getString("vehi_num"));
            amnt.setText(rs.getString("amount"));
            spntdate.setDate(rs.getDate("date"));
            ty.setSelectedItem(rs.getString("exp_type"));
            pay.setText(rs.getString("pid"));
            
       
        }
        catch(Exception e)
        {   
            
            
        
        }
    }//GEN-LAST:event_vctableMouseClicked

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        c.type=rqst.getText();
                c.amount=Double.parseDouble(amnt.getText());
                
                ti.requestIcharges(c.type,c.amount);
                tableload1();        // TODO add your handling code here:
    }//GEN-LAST:event_requestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           vn.setText("WG1234");
                amnt.setText("76000");
                ty.setSelectedItem("Maintenance");
                pay.setText("PI060");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Rtable;
    private javax.swing.JButton add;
    private javax.swing.JTextField amnt;
    private javax.swing.JTextField amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JTextField pay;
    private javax.swing.JButton request;
    private javax.swing.JTextField rqst;
    private com.toedter.calendar.JDateChooser spntdate;
    private javax.swing.JComboBox ty;
    private javax.swing.JButton update;
    private javax.swing.JTable vctable;
    private javax.swing.JTextField vn;
    // End of variables declaration//GEN-END:variables
}
