/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TandIn;
//import classes.DBconnect;
//import classes.TandIManager;
//import classes.Vehicle;
import Classes.Vehicle;
import Classes.TandIManager;
import Classes.*;
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.PreparedStatement;
import db.dbconnct;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Vehicles extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    
    Vehicle v = new Vehicle();
    
    TandIManager ti= new TandIManager();
    
    Validation va= new Validation();

    /**
     * Creates new form Vehicles
     */
    public Vehicles() {
        initComponents();
        //changes the form background color according to time
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        if(amPm.equals("PM")){
        getContentPane().setBackground(Color.lightGray);
        }
        else
          getContentPane().setBackground(Color.decode("#F5F5F5"));  
        
       
        
        conn = dbconnct.connect();
        
        //load table
        //tableload();
    }
        
        public void tableload(){
        
        try{
             
            String sql = "SELECT  vehiclenum as 'Vehicle Number',type as 'Type',purpose as 'Purpose',availability as 'Availability' FROM vehicle";
           pst = (PreparedStatement) conn.prepareStatement(sql);
           rs =pst.executeQuery();
           
           
           
           
           
           vtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        
        
        catch(Exception e){
            
        }
        
    
    }
        
         public void tableload1(String key){
        
        try{
             
            String sql = "SELECT vehiclenum as 'Vehicle Number',type as 'Type',purpose as 'Purpose',availability as 'Availability' FROM vehicle WHERE  vehiclenum='"+key+"' ";
           pst = (PreparedStatement) conn.prepareStatement(sql);
           rs =pst.executeQuery();
           vtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
           
           
           
           
           
           
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        srch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        vn = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        purpose = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        avlblty = new javax.swing.JComboBox();
        demo = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        vtable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 696));

        p1.setBackground(new java.awt.Color(0, 153, 153));

        search.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Search_26px_16.png")); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Vehicle Number");

        vn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnActionPerformed(evt);
            }
        });
        vn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vnKeyTyped(evt);
            }
        });

        l2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Type");

        l3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Purpose");

        purpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeActionPerformed(evt);
            }
        });
        purpose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                purposeKeyTyped(evt);
            }
        });

        save.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Add_New_26px_13.png")); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        l4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Availability");

        avlblty.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        avlblty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check availability", "Yes", "No" }));

        demo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        demo.setText("Demo");
        demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(l1))
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(vn))
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(demo)
                                .addGap(14, 14, 14))))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l2)
                                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25))
                            .addGroup(p1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(purpose)
                            .addComponent(avlblty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avlblty))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(demo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        vtable.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        vtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehicle Number", "Type", "Purpose", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtableMouseClicked(evt);
            }
        });
        table.setViewportView(vtable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_purposeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String vid=srch.getText();
       
        
        tableload1(vid);
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          boolean x = va.isValidVehiNum(vn.getText());
         
         if(x==true)
         {
             vn.getText();
             
             
         }
          else
            JOptionPane.showMessageDialog(null," Invalid vehicle number");
            
          if(vn.getText().isEmpty() || type.getText().isEmpty() || purpose.getText().isEmpty() || avlblty.getSelectedIndex()==-1)
                         JOptionPane.showMessageDialog(null,"Please fill all the fields");
          else{
          v.vid=vn.getText();
          v.type=type.getText();
          v.purpose=purpose.getText();
          v.availability=avlblty.getSelectedItem().toString();
          
          
       
          
          ti.addvehicles(v.availability,v.type,v.vid,v.purpose);
          tableload();
          
          }
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
          boolean x = va.isValidVehiNum(vn.getText());
         
         if(x==true)
         {
             vn.getText();
             
             
         }
          else
            JOptionPane.showMessageDialog(null," Invalid vehicle number");
          
        
        
        
          if(vn.getText().isEmpty() || type.getText().isEmpty() || purpose.getText().isEmpty() || avlblty.getSelectedIndex()==-1)
                         JOptionPane.showMessageDialog(null,"Please fill all the fields");
          else{
          v.vid=vn.getText();
          v.type=type.getText();
          v.purpose=purpose.getText();
          v.availability=avlblty.getSelectedItem().toString();
          
          ti.updatevehicles(v.availability,v.type,v.vid,v.purpose);
          tableload();
          }// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void vtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtableMouseClicked
        
  int r = vtable.getSelectedRow();
        
        String id= vtable.getValueAt(r, 0).toString();
        
        String sql = "SELECT  vehiclenum,type,purpose,availability FROM vehicle WHERE  vehiclenum='"+id+"' ";
        try{
           pst = (PreparedStatement) conn.prepareStatement(sql);
           rs =pst.executeQuery();
           rs.next();
           
           vn.setText(rs.getString("vehiclenum"));
           type.setText(rs.getString("type"));
           purpose.setText(rs.getString("purpose"));
           avlblty.setSelectedItem(rs.getString("availability"));
        } 
        catch(Exception e){
                
                }
    }//GEN-LAST:event_vtableMouseClicked

    private void vnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnActionPerformed
        
    }//GEN-LAST:event_vnActionPerformed

    private void vnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vnKeyTyped
         
        // TODO add your handling code here:
    }//GEN-LAST:event_vnKeyTyped

    private void purposeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_purposeKeyTyped
        
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeKeyTyped

    private void demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoActionPerformed
        vn.setText("KP1234");
           type.setText("Bus");
           purpose.setText("Transporting employee");
           avlblty.setSelectedItem("Yes");         // TODO add your handling code here:
    }//GEN-LAST:event_demoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox avlblty;
    private javax.swing.JButton demo;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JPanel p1;
    private javax.swing.JTextField purpose;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField srch;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField type;
    private javax.swing.JButton update;
    private javax.swing.JTextField vn;
    private javax.swing.JTable vtable;
    // End of variables declaration//GEN-END:variables
}
