
package HR;

import Classes.Employee;
import Classes.HRmanager;
import Classes.Validation;
//import Classes.dbConnect;
import db.dbconnct;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shanika
 */
public class EditEmployee1 extends javax.swing.JInternalFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs = null;
    
    Employee e = new Employee();
    HRmanager h = new HRmanager();
    
    public EditEmployee1() {
        initComponents();
        
        conn=dbconnct.connect();
        
         //changes the form background color according to time
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        if(amPm.equals("PM")){
        getContentPane().setBackground(Color.lightGray);
        }
        else
          getContentPane().setBackground(Color.decode("#F5F5F5"));  
        
    }
    
    public void tableload(String em){
    
        try{
            String sql = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE Employee_ID LIKE '%"+ em +"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            emptable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emptable = new javax.swing.JTable();
        sbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        schoose = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        efname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        elname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edesig = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eNIC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edep = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eadd = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        ephone = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bday = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ebdate = new javax.swing.JTextField();
        estat = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        etype = new javax.swing.JComboBox();
        ejoined = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Edit Employee");

        emptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Birthday", "Status", "Email", "Designation", "Type", "Joined date", "NIC", "Department", "Address", "Phone No"
            }
        ));
        emptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emptable);

        sbox.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        sbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("Search by : ");

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Search_26px.png")); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        schoose.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        schoose.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EmpID", "Fname", "Lname", "NIC", "Designation" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        efname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efnameActionPerformed(evt);
            }
        });
        efname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                efnameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("First name : ");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setText("Last Name :");

        elname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elnameActionPerformed(evt);
            }
        });
        elname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elnameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel5.setText("Designation : ");

        edesig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edesigKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel6.setText("NIC : ");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel7.setText("Department : ");

        edep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select Department--", "Human Resource", "Finance", "Floor", "Customer", "Inventory", "Event", "Entertainment", "Car Park" }));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel8.setText("Address : ");

        eadd.setColumns(20);
        eadd.setRows(5);
        jScrollPane2.setViewportView(eadd);

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel9.setText("Phone number : ");

        ephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ephoneKeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Available_Updates_26px.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        bday.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        bday.setText("Birthday :");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel11.setText("Civil status :");

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel12.setText("Email :");

        ebdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebdateActionPerformed(evt);
            }
        });
        ebdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ebdateKeyTyped(evt);
            }
        });

        estat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatActionPerformed(evt);
            }
        });
        estat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estatKeyTyped(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel13.setText("Type :");

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel14.setText("Joined Date :");

        etype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Select Type----", "Full-time", "Part-time", "Fixed-term", "Daily hire", "" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(efname, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ebdate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edep, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ejoined, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eNIC)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etype, 0, 1, Short.MAX_VALUE)
                            .addComponent(edesig, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ephone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(eNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(edep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(efname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(elname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bday, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ebdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ejoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel1.setText("Employee ID : ");

        eid.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        eid.setText("NULL");

        jButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anu\\AppData\\Local\\Temp\\icons8_Trash_Can_26px.png")); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(eid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eid))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sbox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(schoose, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(schoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       if(eid.getText().isEmpty() || efname.getText().isEmpty() || elname.getText().isEmpty() || ebdate.getText().isEmpty() || estat.getText().isEmpty() || email.getText().isEmpty() || edesig.getText().isEmpty() || etype.getSelectedItem().toString().isEmpty() || eNIC.getText().isEmpty() || edep.getSelectedItem().toString().isEmpty() || efname.getText().isEmpty() || eadd.getText().isEmpty() || ephone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
        }
       else{
       int x =  JOptionPane.showConfirmDialog(null,"Do you really want to update?");
       
       if(x==0){
           
           Validation v = new Validation();

            if(v.isNumeric(efname.getText())){
            JOptionPane.showMessageDialog(null,"Enter first name again!");
            }else if(v.isNumeric(elname.getText())){
            JOptionPane.showMessageDialog(null,"Enter last name again!");
            }else if((v.isNumeric(edesig.getText()))){
            JOptionPane.showMessageDialog(null,"Enter designation again!");
            }else if(!v.CheckNIC(eNIC.getText())){  
            JOptionPane.showMessageDialog(null,"Enter NIC again!");
            }else if(v.isNumeric(estat.getText())){  
            JOptionPane.showMessageDialog(null,"Enter status again!");
            }else if(v.CheckEmail(email.getText())){  
            JOptionPane.showMessageDialog(null,"Enter email again!");
            }
            else if(edep.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null,"Enter department again");
            }else if(!v.isVaildContactNo(ephone.getText())){
            JOptionPane.showMessageDialog(null,"Enter Phone number again!");
            }
            //
            else {
               
                SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
                
                e.Empid = eid.getText();
                e.fname = efname.getText();
                e.lname = elname.getText();
                e.birthday = ebdate.getText();
                e.stat = estat.getText();
                e.email = email.getText();
                e.designation = edesig.getText();
                e.type = etype.getSelectedItem().toString();
                e.jdate = d.format(ejoined.getDate());
                e.NIC = eNIC.getText();
                e.dep = edep.getSelectedItem().toString();
                e.address = eadd.getText();
                e.phone = ephone.getText();
        
                h.updateemp(e.Empid,e.fname,e.lname,e.birthday,e.stat,e.email,e.designation,e.type,e.jdate,e.NIC,e.dep,e.address,e.phone);
        
                tableload(e.Empid);
            }
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptableMouseClicked
       
        int r = emptable.getSelectedRow();
        
        e.Empid = emptable.getValueAt(r, 0).toString();
        e.fname = emptable.getValueAt(r, 1).toString();
        e.lname = emptable.getValueAt(r, 2).toString();
        e.birthday = emptable.getValueAt(r, 3).toString();
        e.stat = emptable.getValueAt(r, 4).toString();
        e.email = emptable.getValueAt(r, 5).toString();
        e.designation = emptable.getValueAt(r, 6).toString();
        e.type = emptable.getValueAt(r, 7).toString();
        e.jdate = emptable.getValueAt(r, 8).toString();
        e.NIC = emptable.getValueAt(r, 9).toString();
        e.dep = emptable.getValueAt(r, 10).toString();
        e.address = emptable.getValueAt(r, 11).toString();
        e.phone = emptable.getValueAt(r, 12).toString();
        
        
        
        eid.setText(e.Empid);
        efname.setText(e.fname);
        elname.setText(e.lname);
        ebdate.setText(e.birthday);
        estat.setText(e.stat);
        email.setText(e.email);
        edesig.setText(e.designation);
        etype.setSelectedItem(e.type);
        eNIC.setText(e.NIC);
        edep.setSelectedItem(e.dep);
        eadd.setText(e.address);
        ephone.setText(e.phone);
         
        
        
    }//GEN-LAST:event_emptableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        eid.setText("");
        efname.setText("");
        elname.setText("");
        ebdate.setText(null);
        estat.setText("");
        email.setText(null);
        edesig.setText("");
        etype.setSelectedIndex(0);
        ejoined.setDate(null);
        eNIC.setText("");
        edep.setSelectedIndex(0);
        eadd.setText("");
        ephone.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void efnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_efnameKeyTyped
        
        char c=evt.getKeyChar();

        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE )){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Numbers are not allowed in this field");
        }
    }//GEN-LAST:event_efnameKeyTyped

    private void elnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elnameKeyTyped
        
        char c=evt.getKeyChar();

        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE )){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Numbers are not allowed in this field");
        }
    }//GEN-LAST:event_elnameKeyTyped

    private void edesigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edesigKeyTyped
       
        char c=evt.getKeyChar();

        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE )){
        evt.consume();
        JOptionPane.showMessageDialog(null,"Numbers are not allowed in this field");
        }
    }//GEN-LAST:event_edesigKeyTyped

    private void ephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ephoneKeyTyped

        
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Characters are not allowed in this field!");
    }
    }//GEN-LAST:event_ephoneKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(sbox.getText().isEmpty())
        JOptionPane.showMessageDialog(null,"This field cannot be empty!");
        else{
            String v = sbox.getText();
            String ch = schoose.getSelectedItem().toString();

            switch(ch){
                case "EmpID":
                String sq4 = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE Employee_ID LIKE '%"+ v +"%'";

                try {
                    pst = conn.prepareStatement(sq4);
                    pst.execute();
                    rs=pst.executeQuery();

                    emptable.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Incorrect Value"+ex);
                }
                break;
                case "Fname":
                String sq3 = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE First_name LIKE '%"+ v +"%'";

                try {
                    pst = conn.prepareStatement(sq3);
                    pst.execute();
                    rs=pst.executeQuery();

                    emptable.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Incorrect Value"+ex);
                }
                break;
                case "Lname":
                String sq2 = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE Last_name LIKE '%"+ v +"%'";

                try {
                    pst = conn.prepareStatement(sq2);
                    pst.execute();
                    rs=pst.executeQuery();

                    emptable.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Incorrect Value"+ex);
                }
                break;
                case "Designation":
                String sq1 = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE Designation LIKE '%"+ v +"%'";

                try {
                    pst = conn.prepareStatement(sq1);
                    pst.execute();
                    rs=pst.executeQuery();

                    emptable.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Incorrect Value"+ex);
                }
                break;
                case "NIC":
                String sq = "SELECT Employee_ID,First_name,Last_name,Birthday,Civil_status,Email,Designation,Emp_type,Joined_date,NIC,Department,Address,Phone_no FROM employee WHERE NIC LIKE '%"+ v +"%'";

                try {
                    pst = conn.prepareStatement(sq);
                    pst.execute();
                    rs=pst.executeQuery();

                    emptable.setModel(DbUtils.resultSetToTableModel(rs));

                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Incorrect Value"+ex);
                }
                break;
            }
    }//GEN-LAST:event_jButton1ActionPerformed
 }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        e.Empid = eid.getText();
        
        if(e.Empid==""){
            JOptionPane.showMessageDialog(null,"This field cannot be empty");
        }
        else{
        int x =  JOptionPane.showConfirmDialog(null,"Do you really want to delete?");

        if(x==0){
           
            h.delemp(e.Empid);

            tableload(e.Empid);
            eid.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        eid.setText("");
        efname.setText("");
        elname.setText("");
        ebdate.setText(null);
        estat.setText("");
        email.setText(null);
        edesig.setText("");
        etype.setSelectedIndex(0);
        ejoined.setDate(null);
        eNIC.setText("");
        edep.setSelectedIndex(0);
        eadd.setText("");
        ephone.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void efnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efnameActionPerformed

    private void ebdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebdateActionPerformed

    private void ebdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ebdateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ebdateKeyTyped

    private void estatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estatActionPerformed

    private void estatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_estatKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyTyped

    private void sboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bday;
    private javax.swing.JTextField eNIC;
    private javax.swing.JTextArea eadd;
    private javax.swing.JTextField ebdate;
    private javax.swing.JComboBox edep;
    private javax.swing.JTextField edesig;
    private javax.swing.JTextField efname;
    private javax.swing.JLabel eid;
    private com.toedter.calendar.JDateChooser ejoined;
    private javax.swing.JTextField elname;
    private javax.swing.JTextField email;
    private javax.swing.JTable emptable;
    private javax.swing.JTextField ephone;
    private javax.swing.JTextField estat;
    private javax.swing.JComboBox etype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField sbox;
    private javax.swing.JComboBox schoose;
    // End of variables declaration//GEN-END:variables
}
